// <auto-generated />
using GymShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymShop.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20250525101452_Products")]
    partial class Products
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymShop.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            ProductName = "Whey Protein",
                            ProductPrice = 29.989999999999998,
                            ProductQuantity = 50
                        },
                        new
                        {
                            ProductID = 2,
                            ProductName = "Yoga Mat",
                            ProductPrice = 19.989999999999998,
                            ProductQuantity = 100
                        },
                        new
                        {
                            ProductID = 3,
                            ProductName = "Dumbbell Set",
                            ProductPrice = 89.989999999999995,
                            ProductQuantity = 20
                        },
                        new
                        {
                            ProductID = 4,
                            ProductName = "Resistance Bands",
                            ProductPrice = 14.99,
                            ProductQuantity = 75
                        },
                        new
                        {
                            ProductID = 5,
                            ProductName = "Kettlebell 16kg",
                            ProductPrice = 39.990000000000002,
                            ProductQuantity = 30
                        },
                        new
                        {
                            ProductID = 6,
                            ProductName = "Foam Roller",
                            ProductPrice = 24.989999999999998,
                            ProductQuantity = 60
                        },
                        new
                        {
                            ProductID = 7,
                            ProductName = "Jump Rope",
                            ProductPrice = 9.9900000000000002,
                            ProductQuantity = 120
                        },
                        new
                        {
                            ProductID = 8,
                            ProductName = "Creatine Monohydrate",
                            ProductPrice = 19.489999999999998,
                            ProductQuantity = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
